In [190]:
!pip install streamlit -q

     |████████████████████████████████| 10.1 MB 3.6 MB/s 
     |████████████████████████████████| 4.3 MB 36.7 MB/s 
     |████████████████████████████████| 77 kB 4.2 MB/s 
     |████████████████████████████████| 164 kB 58.3 MB/s 
     |████████████████████████████████| 181 kB 34.0 MB/s 
     |████████████████████████████████| 111 kB 41.6 MB/s 
     |████████████████████████████████| 63 kB 1.4 MB/s 
     |████████████████████████████████| 131 kB 45.8 MB/s 
     |████████████████████████████████| 130 kB 37.2 MB/s 
     |████████████████████████████████| 793 kB 61.6 MB/s 
     |████████████████████████████████| 428 kB 45.2 MB/s 
     |████████████████████████████████| 381 kB 39.0 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-console 5.2.0 requires prompt-toolkit<2.0.0,>=1.0.0, but you have prompt-toolkit 3.0.29 which is incompatible.
google-colab 1

In [ ]:
# import streamlit as st
# import streamlit.components.v1 as components

# # Connectiong to the Google Drive for the permanent storage
# from google.colab import drive
# drive.mount('/content/drive')

# # >>> import plotly.express as px
# # >>> fig = px.box(range(10))
# # >>> fig.write_html('test.html')

# st.header("test html import")

# HtmlFile = open("/content/drive/MyDrive/MNIST/templetes/index.html", 'r', encoding='utf-8')
# source_code = HtmlFile.read() 
# print(source_code)
# components.html(source_code)

In [208]:
%%writefile app.py

f = open('app.html','w')

message = """<html>
<head></head>
<body><p>Hello World!</p></body>
</html>"""

f.write(message)
f.close()



Overwriting app.py


In [ ]:
# <!DOCTYPE html>
# <html>
# <body>

# <h1>Machine Learning Semester Project</h1>

# <form >
#     <input class="file-upload-input" type="file" onchange="readURL(this)" accept="Image"><br><br>
#     <input type="submit" value="Make Prdiction">
# </form>


# </body>
# </html>


In [210]:
! streamlit run app.html & npx localtunnel --port 8501

2022-05-22 10:18:06.943 INFO    numexpr.utils: NumExpr defaulting to 2 threads.
Usage: streamlit run [OPTIONS] TARGET [ARGS]...

Error: Streamlit requires raw Python (.py) files, not .html.
For more information, please see https://docs.streamlit.io
npx: installed 22 in 3.924s
your url is: https://plain-carrots-know-35-236-176-175.loca.lt
^C


In [1]:
# Connectiong to the Google Drive for the permanent storage
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [93]:
# Checking if the correct version of tensorflow in installed or not 
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


In [94]:
from numpy.random import seed
seed(786)
# Tensor flow for the fast calculation or computation
import tensorflow
tensorflow.random.set_seed(786)

In [95]:
# Other imports like os for directory management and numpy for mathematical operation on arrays
import os

# Numpy for performing mathematical operations on arrays
import numpy as np

# Importing pandas for data visualization in the forms of tables or data frames
import pandas as pd

# Time for dealing with real time and the pillow for dealing with the image for predictions
from time import strftime

# Pillow for the image used for prediction
from PIL import Image

In [96]:
# Loading all the files from the directory into variables
X_TRAINING_PATH =  '/content/drive/MyDrive/MNIST/digit_xtrain.csv'
X_TESTING_PATH =   '/content/drive/MyDrive/MNIST/digit_xtest.csv'
Y_TRAINING_PATH =  '/content/drive/MyDrive/MNIST/digit_ytrain.csv'
Y_TESTING_PATH =   '/content/drive/MyDrive/MNIST/digit_ytest.csv'


In [97]:
%%time
# Geting the wall time required for reading the y-training csv file
y_training_all = np.loadtxt(Y_TRAINING_PATH, delimiter=',', dtype=int)

CPU times: user 203 ms, sys: 2.88 ms, total: 206 ms
Wall time: 219 ms


In [98]:
y_training_all.shape

(60000,)

In [99]:
%%time
y_testing = np.loadtxt(Y_TESTING_PATH, delimiter=',', dtype=int)

CPU times: user 40 ms, sys: 77 µs, total: 40.1 ms
Wall time: 43.7 ms


In [100]:
%%time

x_training_all = np.loadtxt(X_TRAINING_PATH, delimiter=',', dtype=int)

CPU times: user 22.9 s, sys: 2.66 s, total: 25.6 s
Wall time: 25.6 s


In [101]:
%%time

x_testing = np.loadtxt(X_TESTING_PATH, delimiter=',', dtype=int)

CPU times: user 3.79 s, sys: 265 ms, total: 4.06 s
Wall time: 4.1 s


# Visualizing the Dataset

In [102]:
x_training_all.shape

(60000, 784)

In [103]:
x_training_all[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [104]:
y_training_all.shape

(60000,)

In [105]:
x_testing.shape

(10000, 784)

In [106]:
# First 10 labels from training dataset
y_training_all[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4])

In [107]:
# Our Features are between 0 and 255 which is a large range. So, we have to rescale our training and testing dataset
# After rescaling our data is between 0 and 1
x_training_all = x_training_all / 255.0
x_testing      =  x_testing / 255.0

In [108]:
x_training_all[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [109]:
# Our labels are 10 in total from 0 to 9
NR_CLASSES = 10

In [110]:
y_training_all = np.eye(NR_CLASSES)[y_training_all]

In [111]:
y_training_all.shape

(60000, 10)

In [112]:
y_testing = np.eye(NR_CLASSES)[y_testing]
y_testing.shape

(10000, 10)

In [113]:
LOGGING_PATH = '/content/sample_data/MNISTtensorboard_mnist_digit_logs/'

VALIDATION_SIZE = 10000
IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
# Total number of features
TOTAL_INPUTS = IMAGE_WIDTH*IMAGE_HEIGHT*CHANNELS 

In [114]:
# Now we have to divide our training dataset into smaller training and validation dataset
# Training dataset contains 50000 and avalidation contains 10000

In [115]:
# From start to the validation size
x_val = x_training_all[:VALIDATION_SIZE]
y_val = y_training_all[:VALIDATION_SIZE]

In [116]:
x_val.shape

(10000, 784)

In [117]:
# From validation size till the end
x_training = x_training_all[VALIDATION_SIZE:]
y_training = y_training_all[VALIDATION_SIZE:]

In [118]:
x_training.shape

(50000, 784)

# Setup Tensorflow Graph

In [119]:
# Creating tensors
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# tf.placeholder is used for creating tensors 2 parameters (datatype, shape of tensor)
X = tf.placeholder(tf.float32, shape=[None, TOTAL_INPUTS], name='X')
Y = tf.placeholder(tf.float32, shape=[None, NR_CLASSES], name='labels')

In [120]:
# Hyperparameters
# nr_epochs = 25
# learning_rate = 1e-3
nr_epochs = 50
learning_rate = 1e-4

n_hidden1 = 512
n_hidden2 = 64

In [121]:
1e-3

0.001

In [122]:
def setup_layer(input, weight_dim, bias_dim, name):
    
    with tf.name_scope(name):
      """
      Iniatializing the weights
      tf.truncated_normal generates random values execpt for extreme values 
      Shape = no of inputs and neurons in the layer
      Standard Deviation tells how far appart weights should from each others
      """
      initial_w = tf.truncated_normal(shape=weight_dim, stddev=0.1, seed=42)
      # Calculations for weights 
      w = tf.Variable(initial_value=initial_w, name='W')

      """
      Initializing the biases
      All biases start from same value that is 0
      Shape is no of neurons in layer
      """
      initial_b = tf.constant(value=0.0, shape=bias_dim)
      # Calculation of the biases
      b = tf.Variable(initial_value=initial_b, name='B')

      """
      Input layer of next hidden layer
      MatrixMultiplication
      """
      layer_in = tf.matmul(input, w) + b

      # Checking for the the last hidden layer to apply activation accordingly
      if name=='out':
        # Apply softmax for the last layer
        layer_out = tf.nn.softmax(layer_in)
      else:
        # Apply relu for the remaining layers
        layer_out = tf.nn.relu(layer_in)
        
      tf.summary.histogram('weights', w)
      tf.summary.histogram('biases', b)
        
      return layer_out

In [123]:
layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1], 
                      bias_dim=[n_hidden1], name='layer_1')

layer_drop = tf.nn.dropout(layer_1, keep_prob=0.8, name='dropout_layer')

layer_2 = setup_layer(layer_drop, weight_dim=[n_hidden1, n_hidden2], 
                      bias_dim=[n_hidden2], name='layer_2')

output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES], 
                      bias_dim=[NR_CLASSES], name='out')

model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'

# Tensorboard Setup

In [124]:
# Folder for Tensorboard

folder_name = f'{model_name} at {strftime("%H:%M")}'
directory = os.path.join(LOGGING_PATH, folder_name)

try:
    os.makedirs(directory)
except OSError as exception:
    print(exception.strerror)
else:
    print('Successfully created directories!')

Successfully created directories!


# Loss, Optimisation & Metrics

#### Defining Loss Function

In [125]:

with tf.name_scope('loss_calc'):
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=output))

#### Defining Optimizer

In [126]:
with tf.name_scope('optimizer'):
    optimizer = tf.train.AdamOptimizer(learning_rate)
    train_step = optimizer.minimize(loss)

#### Accuracy Metric

In [127]:
with tf.name_scope('accuracy_calc'):
    correct_pred = tf.equal(tf.argmax(output, axis=1), tf.argmax(Y, axis=1))
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

In [128]:
with tf.name_scope('performance'):
    tf.summary.scalar('accuracy', accuracy)
    tf.summary.scalar('cost', loss)

#### Check Input Images in Tensorboard

In [129]:
with tf.name_scope('show_image'):
    x_image = tf.reshape(X, [-1, 28, 28, 1])
    tf.summary.image('image_input', x_image, max_outputs=4)

# Run Session

In [130]:
sess = tf.Session()

#### Setup Filewriter and Merge Summaries

In [131]:
merged_summary = tf.summary.merge_all()

train_writer = tf.summary.FileWriter(directory + '/train')
train_writer.add_graph(sess.graph)

validation_writer = tf.summary.FileWriter(directory + '/validation')

#### Initialise all the variables

In [132]:

init = tf.global_variables_initializer()
sess.run(init)

### Batching the Data

In [133]:
size_of_batch = 1000
# size_of_batch = 500
# size_of_batch = 2000


In [134]:
num_examples = y_training.shape[0]
nr_iterations = int(num_examples/size_of_batch)

index_in_epoch = 0

this function is to go to the next batch


In [135]:
def next_batch(batch_size, data, labels):
    
    global num_examples
    global index_in_epoch
    
    start = index_in_epoch
    index_in_epoch += batch_size
    
    if index_in_epoch > num_examples:
        start = 0
        index_in_epoch = batch_size
    
    end = index_in_epoch
    
    return data[start:end], labels[start:end]

### Training Loop

In [136]:
import array as arr
accuracy_array = []

In [137]:
%%time
for epoch in range(nr_epochs):
    
    # ============= Training Dataset =========
    for i in range(nr_iterations):
        
        batch_x, batch_y = next_batch(batch_size=size_of_batch, data=x_training, labels=y_training)
        
        feed_dictionary = {X:batch_x, Y:batch_y}
        
        sess.run(train_step, feed_dict=feed_dictionary)
        
    
    s, batch_accuracy = sess.run(fetches=[merged_summary, accuracy], feed_dict=feed_dictionary)
        
    train_writer.add_summary(s, epoch)
    
    print(f'Epoch {epoch} \t| Training Accuracy = {batch_accuracy}')
    
    # ================== Validation ======================
    
    summary = sess.run(fetches=merged_summary, feed_dict={X:x_val, Y:y_val})
    validation_writer.add_summary(summary, epoch)

    accuracy_array.append(batch_accuracy)

print('Done training!')

Epoch 0 	| Training Accuracy = 0.5360000133514404
Epoch 1 	| Training Accuracy = 0.7739999890327454
Epoch 2 	| Training Accuracy = 0.7929999828338623
Epoch 3 	| Training Accuracy = 0.8259999752044678
Epoch 4 	| Training Accuracy = 0.8460000157356262
Epoch 5 	| Training Accuracy = 0.8479999899864197
Epoch 6 	| Training Accuracy = 0.8519999980926514
Epoch 7 	| Training Accuracy = 0.8579999804496765
Epoch 8 	| Training Accuracy = 0.8519999980926514
Epoch 9 	| Training Accuracy = 0.859000027179718
Epoch 10 	| Training Accuracy = 0.8560000061988831
Epoch 11 	| Training Accuracy = 0.8600000143051147
Epoch 12 	| Training Accuracy = 0.8610000014305115
Epoch 13 	| Training Accuracy = 0.8600000143051147
Epoch 14 	| Training Accuracy = 0.8600000143051147
Epoch 15 	| Training Accuracy = 0.8619999885559082
Epoch 16 	| Training Accuracy = 0.8629999756813049
Epoch 17 	| Training Accuracy = 0.8669999837875366
Epoch 18 	| Training Accuracy = 0.8690000176429749
Epoch 19 	| Training Accuracy = 0.86500000

In [138]:
# accuracy of the whole training model
accuracy_of_model = np.mean(accuracy_array)
print("Accuracy of model = {}%".format(accuracy_of_model*100))

Accuracy of model = 90.34199714660645%


#Model with Different hyperparameters

In [139]:
# # Hyperparameters
# nr_epochs = 100
# learning_rate = 1e-4

# n_hidden1 = 512
# n_hidden2 = 64

In [140]:
# 1e-4

# Make a Prediction

In [141]:
img = Image.open('/content/drive/MyDrive/MNIST/test_img.png')
img

In [142]:
bw = img.convert('L')

In [143]:
img_array = np.invert(bw)

In [144]:
img_array.shape

(28, 28)

In [145]:
test_img = img_array.ravel()

In [146]:
test_img.shape

(784,)

In [147]:
img_array

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        127, 127,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 127, 127, 190,
        190, 190, 190,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [148]:
prediction = sess.run(fetches=tf.argmax(output, axis=1), feed_dict={X:[test_img]})

In [149]:
print(f'Prediction for test image is {prediction}')

Prediction for test image is [2]


# Testing and Evaluation

In [150]:
test_accuracy = sess.run(fetches=accuracy, feed_dict={X:x_testing, Y:y_testing})
print(f'Accuracy on test set is {test_accuracy:0.2%}')

Accuracy on test set is 95.65%


##Prediction 2

In [151]:
img = Image.open('/content/drive/MyDrive/MNIST/test_img_4.png')
img

In [152]:
bw = img.convert('L')

In [153]:
img_array = np.invert(bw)

In [154]:
img_array.shape

(28, 28)

In [155]:
test_img = img_array.ravel()

In [156]:
test_img.shape

(784,)

In [157]:
img_array

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   1,   2,   1,
          0,   1,   0,   1,   0,   1,   1,   1,   1,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   1,   1,   0,   1,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   1,   1,   0,   8,  22,   5,
          0,   1,   0,   1,   0,   1,   5,   1,   0,   1,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   1,   1,   1,  68, 161,  29,
          0,   2,   0,   1,   0,  10,  62,  42,   4,   0,   1,   0,   0,
          0,   0],
       [  

In [158]:
prediction = sess.run(fetches=tf.argmax(output, axis=1), feed_dict={X:[test_img]})

In [159]:
print(f'Prediction for test image is {prediction}')

Prediction for test image is [4]


# Reset for the Next Run

In [160]:
train_writer.close()
validation_writer.close()
sess.close()
tf.reset_default_graph()

In [161]:
def print_Function():
    print('Hello World')


In [162]:
print_Function()

Hello World


In [163]:
def predict_test_image():
  print('The Result is: __')